[versions]
neogradle = "7.1.0"
loom = "1.11.8"

[libraries]
neogradle-common = { module = "net.neoforged.gradle:common", version.ref = "neogradle" }
loom = { module = "net.fabricmc:fabric-loom", version.ref = "loom" }

[bundles]
platforms = ["neogradle-common", "loom"]
